:project:
  :use_exceptions: FALSE
  :use_auxiliary_dependencies: TRUE
  :build_root: build_test
  :test_file_prefix: test_
  :which_ceedling: gem
  :ceedling_version: 1.0.0
  :default_tasks:
    - test:all

:extension:
  :executable: .out

:paths:
  :test:
    - app/tests/**
  :source:
    - app/**
  :include:
    - app/**

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
    - :callback
  :treat_as:
    uint8:    HEX8
    uint16:   HEX16
    uint32:   UINT32
    int8:     INT8
    bool:     UINT8

:plugins:
  :enabled:
    - report_tests_pretty_stdout
    - module_generator
    - report_tests_log_factory
    
    - gcov
    


:gcov:
  :reports:
    - Html
  :gcovr:
    :use: true


:report_tests_log_factory:
  :reports:
    - junit